version: '3.9'
services:
  ngnix:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress:/var/www/html

  wordpress:
    depends_on:
      - mysql
    image: wordpress:5.9-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=secret
      - WORDPRESS_DB_NAME=wp
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins

    networks:
      - app-network

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - wordpress:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes:
  wordpress:

networks:
  app-network:
    driver: bridge