#!/bin/sh
protected_branch="feature/git_commit_rules"

while read local_ref local_sha remote_ref remote_sha; do
    if [ "$remote_ref" = "refs/heads/$protected_branch" ]; then
        echo "Error: Pushing directly to the '$protected_branch' branch is not allowed."
        exit 1
    fi
done

exit 0